
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5


development:
  <<: *default
  database: DesignaLabs_development
  host: db

test:
  <<: *default
  database: DesignaLabs_test

production:
  <<: *default
  database: DesignaLabs_production
  username: DesignaLabs
  password: <%= ENV['DESIGNALABS_DATABASE_PASSWORD'] %>
